'use client';

/**
 * In-app User Guide viewer. Renders the guide content for the current locale from
 * the pre-built JSON in /public/guides (generated by scripts/build_user_guide.py,
 * the same source as the downloadable .docx files), with a sticky table of
 * contents and Word downloads in all three languages.
 */
import React, { useEffect, useMemo, useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import { PageHeader } from '@/components/layout/page-header';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { LoadingSpinner } from '@/components/ui/loading-spinner';
import { Download, Lightbulb, AlertTriangle, Info, ListTree } from 'lucide-react';

type Block =
  | { type: 'h3' | 'p' | 'tip' | 'warn' | 'info'; text: string }
  | { type: 'ul' | 'ol'; items: string[] };

interface GuideSection { id: string; heading: string; blocks: Block[] }
interface Guide { title: string; subtitle: string; updated: string; tocTitle: string; sections: GuideSection[] }

const DOWNLOADS: { loc: string; label: string }[] = [
  { loc: 'pt-br', label: 'Português (.docx)' },
  { loc: 'en', label: 'English (.docx)' },
  { loc: 'es', label: 'Español (.docx)' },
];

function fileLocale(locale: string): string {
  if (locale.toLowerCase().startsWith('pt')) return 'pt-br';
  if (locale.toLowerCase().startsWith('es')) return 'es';
  return 'en';
}

const CALLOUT = {
  tip: { icon: Lightbulb, cls: 'border-cyan-500/30 bg-cyan-500/10 text-cyan-900 dark:text-cyan-200' },
  warn: { icon: AlertTriangle, cls: 'border-amber-500/30 bg-amber-500/10 text-amber-900 dark:text-amber-200' },
  info: { icon: Info, cls: 'border-primary/30 bg-primary/10 text-primary' },
} as const;

function BlockView({ block }: { block: Block }) {
  switch (block.type) {
    case 'h3':
      return <h3 className="mt-6 mb-2 text-lg font-semibold text-foreground">{block.text}</h3>;
    case 'p':
      return <p className="mb-3 leading-relaxed text-muted-foreground">{block.text}</p>;
    case 'ul':
      return (
        <ul className="mb-3 list-disc space-y-1.5 pl-6 text-muted-foreground">
          {block.items.map((it, i) => <li key={i} className="leading-relaxed">{it}</li>)}
        </ul>
      );
    case 'ol':
      return (
        <ol className="mb-3 list-decimal space-y-1.5 pl-6 text-muted-foreground">
          {block.items.map((it, i) => <li key={i} className="leading-relaxed">{it}</li>)}
        </ol>
      );
    default: {
      const c = CALLOUT[block.type];
      const Icon = c.icon;
      return (
        <div className={`mb-3 flex gap-2 rounded-lg border p-3 text-sm ${c.cls}`}>
          <Icon className="mt-0.5 h-4 w-4 shrink-0" />
          <span className="leading-relaxed">{block.text}</span>
        </div>
      );
    }
  }
}

export default function UserGuidePage() {
  const locale = useLocale();
  const t = useTranslations('userGuide');
  const [guide, setGuide] = useState<Guide | null>(null);
  const [loading, setLoading] = useState(true);

  const fLoc = useMemo(() => fileLocale(locale), [locale]);

  useEffect(() => {
    let active = true;
    setLoading(true);
    fetch(`/guides/user-guide-${fLoc}.json`)
      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then((data: Guide) => { if (active) setGuide(data); })
      .catch(() => { if (active) setGuide(null); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [fLoc]);

  return (
    <div className="space-y-6">
      <PageHeader title={t('title')} description={t('subtitle')} />

      {/* Downloads */}
      <Card>
        <CardContent className="flex flex-wrap items-center gap-3 py-4">
          <span className="text-sm font-medium">{t('downloadLabel')}</span>
          {DOWNLOADS.map((d) => (
            <Button key={d.loc} asChild variant="outline" size="sm">
              <a href={`/guides/user-guide-${d.loc}.docx`} download>
                <Download className="mr-2 h-4 w-4" />
                {d.label}
              </a>
            </Button>
          ))}
        </CardContent>
      </Card>

      {loading ? (
        <div className="flex items-center justify-center min-h-[40vh]">
          <LoadingSpinner size="xl" className="text-primary" />
        </div>
      ) : !guide ? (
        <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">{t('unavailable')}</CardContent></Card>
      ) : (
        <div className="grid gap-6 lg:grid-cols-[260px_1fr]">
          {/* Table of contents */}
          <aside className="hidden lg:block">
            <div className="sticky top-6">
              <p className="mb-3 flex items-center gap-2 text-sm font-semibold">
                <ListTree className="h-4 w-4" /> {guide.tocTitle}
              </p>
              <nav className="space-y-1 text-sm">
                {guide.sections.map((s) => (
                  <a
                    key={s.id}
                    href={`#${s.id}`}
                    className="block rounded px-2 py-1 text-muted-foreground hover:bg-muted hover:text-foreground"
                  >
                    {s.heading}
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Content */}
          <article className="min-w-0 max-w-3xl">
            <p className="mb-6 text-xs text-muted-foreground">{guide.updated}</p>
            {guide.sections.map((s) => (
              <section key={s.id} id={s.id} className="mb-10 scroll-mt-6">
                <h2 className="mb-3 border-b pb-2 text-xl font-bold text-foreground">{s.heading}</h2>
                {s.blocks.map((b, i) => <BlockView key={i} block={b} />)}
              </section>
            ))}
          </article>
        </div>
      )}
    </div>
  );
}
